import Sidebar from '@/components/Layout/Sidebar/Sidebar';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Random Chat App</title>
        <meta name="description" content="Generated by Random Chat App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </>
  );
}

export type MATCH_USER = {
  id: number;
  sent_user: number;
  received_user: number;
  roomkey: string;
  sentuser_superlike: boolean;
  receiveduser_boost: boolean;
  User: {
    account: string;
    name: string;
    job: string;
    age: number;
    id: number;
    Profile_images: [
      {
        url: string;
      }
    ];
  };
  lastchat: {
    chat: string;
    sentAt: string;
    receiver: number;
  };
};
