import Sidebar from '@/components/Sidebar/Sidebar';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Random Chat App</title>
        <meta name="description" content="Generated by Random Chat App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Sidebar />
      </div>
    </>
  );
}
